#!/usr/bin/bash
# ~/.bashrc: executed by bash(1) for non-login shells.
# see /usr/share/doc/bash/examples/startup-files (in the package bash-doc)
# for examples

# fix CURL certificates path
export CURL_CA_BUNDLE=/etc/ssl/certs/ca-certificates.crt
# for linuxbrew
export PATH="$HOME/.linuxbrew/bin:$PATH"
export MANPATH="$HOME/.linuxbrew/share/man:$MANPATH"
export INFOPATH="$HOME/.linuxbrew/share/info:$INFOPATH"

feh --bg-fill backgrounds/desktop_1.png

alias 'firefox'='nohup firefox >& /dev/null &'

# If not running interactively, don't do anything
case $- in
    *i*) ;;
      *) return;;
esac

# don't put duplicate lines or lines starting with space in the history.
# See bash(1) for more options
HISTCONTROL=ignoreboth

# append to the history file, don't overwrite it
shopt -s histappend

# for setting history length see HISTSIZE and HISTFILESIZE in bash(1)
HISTSIZE=1000
HISTFILESIZE=2000

# check the window size after each command and, if necessary,
# update the values of LINES and COLUMNS.
shopt -s checkwinsize

# If set, the pattern "**" used in a pathname expansion context will
# match all files and zero or more directories and subdirectories.
#shopt -s globstar

# make less more friendly for non-text input files, see lesspipe(1)
[ -x /usr/bin/lesspipe ] && eval "$(SHELL=/bin/sh lesspipe)"

# set variable identifying the chroot you work in (used in the prompt below)
if [ -z "${debian_chroot:-}" ] && [ -r /etc/debian_chroot ]; then
    debian_chroot=$(cat /etc/debian_chroot)
fi

# set a fancy prompt (non-color, unless we know we "want" color)
case "$TERM" in
    xterm-color) color_prompt=yes;;
esac

# uncomment for a colored prompt, if the terminal has the capability; turned
# off by default to not distract the user: the focus in a terminal window
# should be on the output of commands, not on the prompt
#force_color_prompt=yes

if [ -n "$force_color_prompt" ]; then
    if [ -x /usr/bin/tput ] && tput setaf 1 >&/dev/null; then
	# We have color support; assume it's compliant with Ecma-48
	# (ISO/IEC-6429). (Lack of such support is extremely rare, and such
	# a case would tend to support setf rather than setaf.)
	color_prompt=yes
    else
	color_prompt=
    fi
fi

if [ "$color_prompt" = yes ]; then
    PS1='${debian_chroot:+($debian_chroot)}\[\033[01;32m\]\u@\h\[\033[00m\]:\[\033[01;34m\]\w\[\033[00m\]\$ '
else
    PS1='${debian_chroot:+($debian_chroot)}\u@\h:\w\$ '
fi
unset color_prompt force_color_prompt

# If this is an xterm set the title to user@host:dir
case "$TERM" in
xterm*|rxvt*)
    PS1="\[\e]0;${debian_chroot:+($debian_chroot)}\u@\h: \w\a\]$PS1"
    ;;
*)
    ;;
esac

# enable color support of ls and also add handy aliases
if [ -x /usr/bin/dircolors ]; then
    test -r ~/.dircolors && eval "$(dircolors -b ~/.dircolors)" || eval "$(dircolors -b)"
    alias ls='ls --color=auto'
    #alias dir='dir --color=auto'
    #alias vdir='vdir --color=auto'

    alias grep='grep --color=auto'
    alias fgrep='fgrep --color=auto'
    alias egrep='egrep --color=auto'
fi

# some more ls aliases
alias ll='ls -alF'
alias lr='ls -ltrh'
alias la='ls -A'
alias l='ls -CF'
# git push alias
#alias gpush='git push -u origin master'

# Add an "alert" alias for long running commands.  Use like so:
#   sleep 10; alert
alias alert='notify-send --urgency=low -i "$([ $? = 0 ] && echo terminal || echo error)" "$(history|tail -n1|sed -e '\''s/^\s*[0-9]\+\s*//;s/[;&|]\s*alert$//'\'')"'

# Alias definitions.
# You may want to put all your additions into a separate file like
# ~/.bash_aliases, instead of adding them here directly.
# See /usr/share/doc/bash-doc/examples in the bash-doc package.

if [ -f ~/.bash_aliases ]; then
    . ~/.bash_aliases
fi

# enable programmable completion features (you don't need to enable
# this, if it's already enabled in /etc/bash.bashrc and /etc/profile
# sources /etc/bash.bashrc).
if ! shopt -oq posix; then
  if [ -f /usr/share/bash-completion/bash_completion ]; then
    . /usr/share/bash-completion/bash_completion
  elif [ -f /etc/bash_completion ]; then
    . /etc/bash_completion
  fi
fi

# added by Anaconda2 2.4.0 installer
export PATH="/home/samhaug/anaconda2/bin:$PATH"

#alias

alias earth='ssh -Y samhaug@earth-nx.earth.lsa.umich.edu'
#alias memex='ssh -Y shaugland@memex.carnegiescience.edu'
#gateway to memex
alias memex='ssh -Y shaugland@ssh.ciw.edu'
alias flux='ssh -Y samhaug@flux-login.arc-ts.umich.edu'
alias pysource='cd ~/anaconda2/lib/python2.7/site-packages'
alias work1='cd ~/work1'
alias clip='pwd | xclip -selection c'

#sac
export SACHOME=/usr/local/sac
. ${SACHOME}/bin/sacinit.sh


#export PATH=$HOME/ScS_reverb_bin:$PATH
##sp_brazil bin
#export PATH=$HOME/sp_brazil_bin:$PATH
#seis_data bin
export PATH=$HOME/seis_process_bin:$PATH
#reflectivity executables
export PATH=$HOME/reflectivity_method/bin:$PATH
#plotting bin
#export PATH=$HOME/pkp_envelope_bin:$PATH
#mendeley bin
export PATH=$HOME/mendeley/bin:$PATH
#xh bin
export PATH=$HOME/xh_compress/src/XH_formatting/bin:$PATH
#sod bin
export PATH=$HOME/sod-3.2.8/bin:$PATH
#TauP bin
export PATH=$HOME/TauP-2.1.2/bin:$PATH
#globus path
export PATH=$HOME/globus:$PATH
#mineos_bin path
export PATH=$HOME/mineos_bin:$PATH
#gemini bin path
export PATH=/home/samhaug/gemini-2.2/setup_bin:$PATH

#python path
#export PYTHONPATH=$PYTHONPATH:/home/samhaug/Python_mods
export EDITOR=vim
#hudson code
export PATH=$HOME/PROGRAMS.330/bin:$PATH
#set printer default
export PRINTER=KONICA-MINOLTA-C250
. /home/samhaug/.axisem3d_roots

#Jeroen CMT harvard
export UTILS="$HOME/CMT_catalog_tools/Utils"
export PATH=$HOME/CMT_catalog_tools/bin:$PATH

# linuxbrew
export PATH="$HOME/.linuxbrew/bin:$PATH"
export MANPATH="$HOME/.linuxbrew/share/man:$MANPATH"
export INFOPATH="$HOME/.linuxbrew/share/info:$INFOPATH"

ulimit -S -s unlimited
